/**
 * AN preset generation: the `an` agent preset written into the dsh user
 * preset root (`$DSH_HOME/.agent-presets/an`). The composition is generated,
 * not templated: the bundled-skills directory is baked in as an absolute path
 * at install time, and the tools row mounts this package's own
 * `lib/tools.js` plugin file, so no `!!js` expression is needed.
 * @module agent-notes-toolkit/preset
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

/** The dsh harness home; defaults to `$DSH_HOME` or `~/.dsh`. */
export function dshHome() {
  return process.env.DSH_HOME ?? join(homedir(), '.dsh')
}

/** The user preset root dsh-agent-presets scans (`includeUserRoot`). */
export function userPresetRoot() {
  return join(dshHome(), '.agent-presets')
}

/** Directory the `an` preset is written into. */
export function anPresetDir() {
  return join(userPresetRoot(), 'an')
}

/** Absolute directory of the bundled skills inside this package. */
export function bundledSkillsDir() {
  return fileURLToPath(new URL('../skills/', import.meta.url))
}

/** Absolute path of the tools plugin file shipped by the dsh-an package. */
export function toolsPluginPath() {
  return fileURLToPath(new URL('../packages/dsh-an/lib/tools.js', import.meta.url))
}

/** The preset composition rows, generated with absolute paths. */
export function presetComposition(skillsDir) {
  return [
    '# AN mode preset: the Agent Notes workflow composition.',
    '# Generated by `an preset-install`; regenerate after reinstalling the toolkit.',
    '- id: persona',
    "  name: '@deepseek-ai/dsh-persona'",
    '  config:',
    '    text: >-',
    '      You are an agent in AN mode (Agent Notes workflow). Every non-trivial change ships with an Agent Note under `.agents/notes`; write or update the owning note, run `notes-verify` until it passes, and keep implemented notes current with what actually shipped.',
    '- id: an-skills',
    "  name: '@deepseek-ai/dsh-skill-filesystem'",
    '  config:',
    '    providerName: an-preset',
    '    includeDefaultRoots: true',
    `    customSkillDirs: [${JSON.stringify(resolve(skillsDir))}]`,
    '- id: an-tools',
    `  name: ${toolsPluginPath()}`,
    '- id: an-instructions',
    "  name: '@deepseek-ai/dsh-agent-instructions'",
    '  config:',
    '    maxBytes: 65536',
    '',
  ].join('\n')
}

/** Preset display metadata for the mode picker. */
export function presetMetadata() {
  return 'name: AN 模式\ndescription: 按 Agent Notes 机制工作：每次非平凡变更都携带决策记录，并以工具与门禁强制格式与链接。\n'
}

/**
 * Install (or reinstall) the AN preset into the dsh user preset root.
 * @returns {{ dir: string, files: string[] }} the written location and files.
 */
export function runPresetInstall() {
  const dir = anPresetDir()
  mkdirSync(dir, { recursive: true })
  const files = ['agent.cordis.yml', 'metadata.yml']
  writeFileSync(join(dir, files[0]), presetComposition(bundledSkillsDir()))
  writeFileSync(join(dir, files[1]), presetMetadata())
  return { dir, files }
}
