/**
 * AN preset generation: the `an` agent preset written into the dsh user
 * preset root (`$DSH_HOME/.agent-presets/an`). The composition is generated,
 * not templated: the bundled-skills directory is baked in as an absolute path
 * at install time, and the tools row mounts this package's own
 * `lib/tools.js` plugin file, so no `!!js` expression is needed.
 * @module agent-notes-toolkit/preset
 */

import { createRequire } from 'node:module'
import { mkdirSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

/** The dsh harness home; defaults to `$DSH_HOME` or `~/.dsh`. */
export function dshHome() {
  return process.env.DSH_HOME ?? join(homedir(), '.dsh')
}

/** The user preset root dsh-agent-presets scans (`includeUserRoot`). */
export function userPresetRoot() {
  return join(dshHome(), '.agent-presets')
}

/** Directory the `an` preset is written into. */
export function anPresetDir() {
  return join(userPresetRoot(), 'an')
}

/**
 * The tools row specifier: the installed dsh-an package's own plugin file when
 * it resolves from this toolkit installation, otherwise the package subpath
 * name the preset mount resolves from the harness/profile base. A package name
 * lets the discovery health check report a missing install instead of baking a
 * dead path.
 */
export function toolsPluginRow() {
  try {
    const manifest = createRequire(import.meta.url).resolve('@liangminhua/dsh-an/package.json')
    return join(manifest, '..', 'lib', 'tools.js')
  } catch {
    return '@liangminhua/dsh-an/tools'
  }
}

/** The preset composition rows, generated with the resolved tools row. */
export function presetComposition() {
  return [
    '# AN mode preset: the Agent Notes workflow composition.',
    '# Generated by `an preset-install`; regenerate after reinstalling the toolkit.',
    '- id: persona',
    "  name: '@deepseek-ai/dsh-persona'",
    '  config:',
    '    text: >-',
    '      You are an agent in AN mode (Agent Notes workflow). Every non-trivial change ships with an Agent Note under `.agents/notes`; write or update the owning note, run `notes-verify` until it passes, and keep implemented notes current with what actually shipped.',
    // The bundled AN skills arrive through the tools plugin's runtime
    // registrations — one delivery channel, so a skills row here would
    // register the same names twice under different providers.
    '- id: an-tools',
    `  name: '${toolsPluginRow()}'`,
    '- id: an-instructions',
    "  name: '@deepseek-ai/dsh-agent-instructions'",
    '  config:',
    '    maxBytes: 65536',
    '',
  ].join('\n')
}

/** Preset display metadata for the mode picker. */
export function presetMetadata() {
  return 'name: AN 模式\ndescription: 按 Agent Notes 机制工作：每次非平凡变更都携带决策记录，并以工具与门禁强制格式与链接。\n'
}

/**
 * Install (or reinstall) the AN preset into the dsh user preset root.
 * @returns {{ dir: string, files: string[] }} the written location and files.
 */
export function runPresetInstall() {
  const dir = anPresetDir()
  mkdirSync(dir, { recursive: true })
  const files = ['agent.cordis.yml', 'metadata.yml']
  writeFileSync(join(dir, files[0]), presetComposition())
  writeFileSync(join(dir, files[1]), presetMetadata())
  return { dir, files }
}
